trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    regionName: 'us-east-1'
    stackName: 'ToDoWebAppBucketCloudformationBackend'
    templateSource: 'file'
    templateFile: 'CloudformationTemplates/CreateBucket.yml'