trigger:
  branches:
    include:
      - cdk

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: |
    npm install -g aws-cdk
    echo
    echo "Checking folder"
    cd CDK
    echo
    echo "Checking contents of folder"
    ls -l
    echo
    echo "Checking current directory"
    echo "$PWD"
    echo

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'AWS-AzurePipelines'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: |
      cd CDK
      cdk synth