trigger:
  branches:
    include:
      - cdk

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: |
    cd CDK
    sudo npm install -g aws-cdk
    cdk synth

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'AWS-AzurePipelines'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: 'cdk deploy --ci --require-approval never'
    disableAutoCwd: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/CDK'
    failOnStandardError: false

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'AWS-AzurePipelines'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: 'cdk deploy --ci --require-approval never'
    disableAutoCwd: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/CDK'
    failOnStandardError: false
