trigger:
  branches:
    include:
      - cdk

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: |
    npm install -g aws-cdk
    cd CDK
    npm install

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'AWS-AzurePipelines'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: |
      cd CDK
      cdk synth

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'AWS-AzurePipelines'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: |
      cd CDK
      cdk diff

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'AWS-AzurePipelines'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: |
      cd CDK
      cdk deploy --ci --require-approval never