trigger:
  branches:
    include:
      - "main"

pool:
  vmImage: 'ubuntu-latest'

variables:
  BucketTemplateName: 'ToDoWebAppStackTemplates'

steps:
- task: S3Upload@1
  inputs:
    awsCredentials: 'AWS-AzurePipelines'
    regionName: 'us-east-1'
    bucketName: '646515679322-todowebappcloudresources'
    sourceFolder: 'Stacks'
    globExpressions: '*.yml'

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'AWS-AzurePipelines'
    regionName: 'us-east-1'
    stackName: 'ToDoWebApp'
    templateSource: 'file'
    templateFile: 'main.yml'
    capabilityAutoExpand: true