trigger:
  branches:
    include:
      - cdk

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: |
    npm install -g aws-cdk
    cd CDK
    echo $(PWD)
    cdk synth