AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ExportS3BucketName:
    Type: String
    Default: ToDoWebAppStackTemplates

Resources:

  S3BucketBackendToDoWebApp:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-todowebappbackend"
      Tags:
        - Key: "Purpose"
          Value: "Keep the files of the lambda functions used by the app"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  S3ToDoBackendName:
    Value: !Ref S3BucketBackendToDoWebApp