AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation Template for the data layer of a To-do list Web App

Resources:
  ToDoDynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "ID"
            AttributeType: "N"
        KeySchema:
          - AttributeName: "ID"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      UpdateReplacePolicy: "Delete"
      DeletionPolicy: "Delete"

Outputs:
  ToDoDynamoTableName:
    Value: !Ref ToDoDynamoTable
  ToDoDynamoTableArn:
    Value: !GetAtt ToDoDynamoTable.Arn